stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - experiments/spam.csv
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
    - data_ingestion.stratify
    outs:
    - data/raw/train.csv
    - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    params:
    - data_preprocessing.text_clean_params
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/processed
    params:
    - feature_engineering.max_features
    - feature_engineering.ngram_range
    outs:
    - data/feature/X_train.npz
    - data/feature/X_test.npz
    - data/feature/y_train.npy
    - data/feature/y_test.npy

  model_training:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/feature
    params:
    - model_training.grid_search
    - model_training.logistic.fixed_params
    - model_training.logistic.param_grid
    - model_training.svm.fixed_params
    - model_training.svm.param_grid
    - model_training.random_forest.fixed_params
    - model_training.random_forest.param_grid
    outs:
    - models/logistic_model.pkl
    - models/svm_model.pkl
    - models/random_forest_model.pkl
    - results/gridsearch/logistic_results.csv
    - results/gridsearch/svm_results.csv
    - results/gridsearch/random_forest_results.csv
    - results/best_params_logistic.yaml
    - results/best_params_svm.yaml
    - results/best_params_random_forest.yaml

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models
    - data/feature
    params:
    - model_training
    metrics:
    - results/evaluation_results.json
    outs:
    - results/evaluation_summary.yaml
    - results/evaluation_summary.md

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  logistic_model:
    path: models/logistic_model.pkl
    type: model
  random_model:
    path: models/random_forest_model.pkl
    type: model
  svm_model:
    path: models/svm_model.pkl
    type: model
  evaluation_results:
    path: results/evaluation_results.json
    type: eval_results
