stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - experiments/spam.csv
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    params:
      - data_preprocessing.text_clean_params
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed
    params:
      - feature_engineering.max_features
      - feature_engineering.ngram_range
    outs:
      - data/feature/X_train.npz
      - data/feature/X_test.npz
      - data/feature/y_train.npy
      - data/feature/y_test.npy

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/feature
    params:
      - model_training.logistic_params
      - model_training.svm_params
      - model_training.random_forest_params
    outs:
      - models/logistic_model.pkl
      - models/svm_model.pkl
      - models/random_forest_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models  # Now properly tracks all models
    metrics:
      - results/evaluation_results.yaml
      