# params.yaml
data_ingestion:
  test_size: 0.2  # Example value
  random_state: 42

data_preprocessing:
  text_clean_params:
    lowercase: true
    remove_urls: true

feature_engineering:
  max_features: 1000
  ngram_range: [1, 2]

model_training:
  logistic_params:
    C: 1.0
    max_iter: 1000
    penalty: "l2"
    solver: "lbfgs"
    
  svm_params:
    C: 1.0
    kernel: linear
  random_forest_params:
    n_estimators: 100
    max_depth: 20